### ISSUE TITLE
Error! 

### ISSUE THREAD

**Issue by Jovantri10** [xixi52/discord-canvas#13]
``` javascript
image.toBuffer() is not function
```

**Comment by Voxlinou** [comment]
You need to make the add the `await` in
```js
const image = await new Canvas.Goodbye()
```
so that it will wait untill the image loads. If you don't then the code won't wait until the canvas finishes loading and will create an error when seeing
```js
image.toBuffer()
```
Hope i helped

**Comment by Jovantri10** [comment]
tysm, its work❤❤👌

**Comment by Voxlinou** [comment]
np
