### ISSUE TITLE
My code doesnt work 

### ISSUE THREAD

**Issue by tovade** [xixi52/discord-canvas#14]
const { MessageEmbed, MessageAttachment } = require("discord.js");
const db = require('quick.db')
const canvas = require("discord-canvas")
module.exports = {
  name: "guildMemberAdd",
  async execute(client, member) {
    let welcomeChannel = db.get(`welchannel_${member.guild.id}`);
  
    if(welcomeChannel === null) {
      return;
    }
    let autoRole = db.get(`welcomerole_${member.guild.id}`);
    if (autoRole === null || !autoRole) return;
    const avatar = member.displayAvatarURL({ dynamic: true });
    const membercount = message.guild.memberCount;
   
  let image = new canvas.Welcome()
    .setUsername(`${member.username}`)
    .setDiscriminator(`${member.discriminator}`)
    .setMemberCount(membercount)
    .setGuildName(`${member.guild.name}`)
    .setAvatar(avatar)
    .setColor("border", "#8015EA")
    .setColor("username-box", "#8015EA")
    .setColor("discriminator-box", "#8015EA")
    .setColor("message-box", "#8015EA")
    .setColor("title", "#8015EA")
    .setColor("avatar", "#8015EA")
    .setBackground("https://www.osustuff.org/img/imageslice/2020-09-22/128949/710153.jpg")
    .toAttachment();
  
  let attachment = new MessageAttachment(image.toBuffer(), "welcome-image.png");
  
   client.channels.cache.get(welcomeChannel).send(attachment)
        member.roles.add(autoRole.id);
        

  }
}

**Comment by hiro-akiba** [comment]
```js
const { MessageEmbed, MessageAttachment } = require("discord.js");
const db = require('quick.db')
const canvas = require("discord-canvas")

module.exports = async () => {
  name: "guildMemberAdd",
  execute(client, member) {

let welcomeChannel = db.get(welchannel_${member.guild.id});

if(welcomeChannel === null) return;
let autoRole = db.get(`welcomerole_${member.guild.id}`);
if (autoRole === null || !autoRole) return;
 const avatar = member.displayAvatarURL({ dynamic: true });
 const membercount = message.guild.memberCount;
 let image = new canvas.Welcome()
  .setUsername(${member.username})
  .setDiscriminator(${member.discriminator})
  .setMemberCount(membercount)
  .setGuildName(${member.guild.name})
  .setAvatar(avatar)
  .setColor("border", "#8015EA")
  .setColor("username-box", "#8015EA")
  .setColor("discriminator-box", "#8015EA")
  .setColor("message-box", "#8015EA")
  .setColor("title", "#8015EA")
  .setColor("avatar", "#8015EA")
  .setBackground("https://www.osustuff.org/img/imageslice/2020-09-22/128949/710153.jpg")
  .toAttachment();

let attachment = new MessageAttachment(image.toBuffer(), "welcome-image.png");

client.channels.cache.get(welcomeChannel).send(attachment)
member.roles.cache.add(autoRole.id);
}
}
```
1. You'll have to await Canvas.Welcome since loading it takes a lot of time
2. In v12 you'll have to use `cache` before `roles` if you want to remove or add one

Hope i helped !

**Comment by tovade** [comment]
> ```js
> 
> const { MessageEmbed, MessageAttachment } = require("discord.js");
> 
> const db = require('quick.db')
> 
> const canvas = require("discord-canvas")
> 
> 
> 
> module.exports = async () => {
> 
>   name: "guildMemberAdd",
> 
>   execute(client, member) {
> 
> 
> 
> let welcomeChannel = db.get(welchannel_${member.guild.id});
> 
> 
> 
> if(welcomeChannel === null) return;
> 
> let autoRole = db.get(`welcomerole_${member.guild.id}`);
> 
> if (autoRole === null || !autoRole) return;
> 
>  const avatar = member.displayAvatarURL({ dynamic: true });
> 
>  const membercount = message.guild.memberCount;
> 
>  let image = new canvas.Welcome()
> 
>   .setUsername(${member.username})
> 
>   .setDiscriminator(${member.discriminator})
> 
>   .setMemberCount(membercount)
> 
>   .setGuildName(${member.guild.name})
> 
>   .setAvatar(avatar)
> 
>   .setColor("border", "#8015EA")
> 
>   .setColor("username-box", "#8015EA")
> 
>   .setColor("discriminator-box", "#8015EA")
> 
>   .setColor("message-box", "#8015EA")
> 
>   .setColor("title", "#8015EA")
> 
>   .setColor("avatar", "#8015EA")
> 
>   .setBackground("https://www.osustuff.org/img/imageslice/2020-09-22/128949/710153.jpg")
> 
>   .toAttachment();
> 
> 
> 
> let attachment = new MessageAttachment(image.toBuffer(), "welcome-image.png");
> 
> 
> 
> client.channels.cache.get(welcomeChannel).send(attachment)
> 
> member.roles.cache.add(autoRole.id);
> 
> }
> 
> }
> 
> ```
> 
> 1. You'll have to await canvas.Welcome() since loading it takes a lot of time
> 
> 2. In v12 you'll have to use `cache` before `roles` if you want to remove or add one
> 
> 
> 
> Hope i helped !

you dont need to add cache though.... to the roles member.roles.add doesnt need cache
