### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by DaatUserName** [xixi52/discord-canvas#25]
I get this error Error: Unsupported image type. How can I fix it...

Image url: https://i.imgur.com/jwSU08a.jpg

**Comment by Shadyyey** [comment]
@DaatUserName The package can't get the image because it's not on discord. Try uploading the image onto discord and try again.

**Comment by DaatUserName** [comment]
Ok thanks

**Comment by DaatUserName** [comment]
Still didn't work

**Comment by sudis** [comment]
Hello you probably use `message.author.avatarURL({dynamic: true})` things. You're must use `png` format on avatars. So you try this: `message.author.avatarURL({dynamic: true, format: "png"})`.

Sincerely.
