### ISSUE TITLE
TypeError: image.toBuffer is not a function

### ISSUE THREAD

**Issue by BlackKnight683** [xixi52/discord-canvas#35]
im using the default welcome message code and it says image.toBuffer is not a function

My code:~
```js
    bot.on("guildMemberAdd", async member => {
      if(!member.guild) return;
      const channel = await db.fetch(`WELCOME-${member.guild.id}`);
      if(!channel) return;

      const image = new Canvas.Welcome()
      .setUsername(member.user.username)
      .setDiscriminator(member.user.discriminator)
      .setMemberCount(member.guild.memberCount.toLocaleString())
      .setGuildName(member.guild.name)
      .setAvatar(member.user.displayAvatarURL())
      .setColor("border", "#6edb90")
      .setColor("username-box", "#6edb90")
      .setColor("discriminator-box", "#6edb90")
      .setColor("message-box", "#6edb90")
      .setColor("title", "#6edb90")
      .setColor("avatar", "#6edb90")
      .setText("member-count", "- {count}th Member!")
      .setText("title", "New User")
      .setText("message", "Welcome new user!")


      const attachment = new Discord.MessageAttachment(image.toBuffer(), "welcome-image.png");
 
       bot.channels.cache.get(channel).send(attachment);
    })
    ```

**Comment by Yan-Jobs** [comment]
You have forget the `  .toAttachment();` here:
`js 
    bot.on("guildMemberAdd", async member => {
      if(!member.guild) return;
      const channel = await db.fetch(`WELCOME-${member.guild.id}`);
      if(!channel) return;

      const image = new Canvas.Welcome()
      .setUsername(member.user.username)
      .setDiscriminator(member.user.discriminator)
      .setMemberCount(member.guild.memberCount.toLocaleString())
      .setGuildName(member.guild.name)
      .setAvatar(member.user.displayAvatarURL())
      .setColor("border", "#6edb90")
      .setColor("username-box", "#6edb90")
      .setColor("discriminator-box", "#6edb90")
      .setColor("message-box", "#6edb90")
      .setColor("title", "#6edb90")
      .setColor("avatar", "#6edb90")
      .setText("member-count", "- {count}th Member!")
      .setText("title", "New User")
      .setText("message", "Welcome new user!")
      .toAttachment();


      const attachment = new Discord.MessageAttachment(image.toBuffer(), "welcome-image.png");
 
       bot.channels.cache.get(channel).send(attachment);
    })`

**Comment by Yan-Jobs** [comment]
@BlackKnight683

**Comment by BlackKnight683** [comment]
Thanks
