### ISSUE TITLE
xp and needed xp?

### ISSUE THREAD

**Issue by setsuk12** [xixi52/discord-canvas#38]
what is the field to modify the xp bar in the canvas?

![dd](https://user-images.githubusercontent.com/82325329/119051895-11e6d080-b9c4-11eb-8382-79746ad932e6.png)

i tried    
.setxpCurrent()
.setxpNeeded()
but it doesn't work, what is the exact value please?
Thanks

**Comment by Yan-Jobs** [comment]
Like that: 
```js
   .setXP("current", 500)
    .setXP("needed", 1000)```
__**READ THE README PLS**__
