### ISSUE TITLE
v13 is broken

### ISSUE THREAD

**Issue by ThatGuyJamal** [xixi52/discord-canvas#42]
Hello, are you doing to upgrade to v13? Most of the package is broken for v13.

**Comment by Shadyyey** [comment]
Hey @ThatGuyJamal, we are currently working for the newer version of discord.js. For now you can use our package, on discord.js version 12.5.3.

**Comment by ThatGuyJamal** [comment]
So your saying your building a new package? Or just working on upgrading it?

**Comment by Shadyyey** [comment]
No we are working on updating this package, as you can see by my commits.

**Comment by Shadyyey** [comment]
When i say commits i mean, Pull Requests.

**Comment by ThatGuyJamal** [comment]
okay cool

**Comment by Shadyyey** [comment]
Hey @ThatGuyJamal. It does not appear that, i can talk to xixi about it. And without him/her, we cannot update for our npm package to work. For now you can rely on discord.js v12.5.3.

**Comment by ThatGuyJamal** [comment]
okay, thanks.
