### ISSUE TITLE
Cannot find module 'moment'

### ISSUE THREAD

**Issue by mrLuisFer** [xixi52/discord-canvas#43]
Hi!
I have tried to install discord-canvas, even the **types** but it gives me 404 error so add `@ts-ignore` to be able to run the bot
But when I run the bot, it shows me the error that the moment module is not found

`TypeScript v4.3.5`

![Module Error Preview](https://user-images.githubusercontent.com/65029792/132801263-23d58e13-416e-4a05-9b8a-c6617bd4283a.png)

**Comment by Yan-Jobs** [comment]
The pkg isn't maintened at all :)

**Comment by mrLuisFer** [comment]
> The pkg isn't maintened at all :)

oh ok, thanks for answering

**Comment by xixi52** [comment]
> Hi!
> I have tried to install discord-canvas, even the **types** but it gives me 404 error so add `@ts-ignore` to be able to run the bot
> But when I run the bot, it shows me the error that the moment module is not found
> 
> `TypeScript v4.3.5`
> 
> ![Module Error Preview](https://user-images.githubusercontent.com/65029792/132801263-23d58e13-416e-4a05-9b8a-c6617bd4283a.png)

Try « npm i moment »
