### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by Akihiro0666** [xixi52/discord-canvas#44]
![image](https://user-images.githubusercontent.com/90979570/133896095-a5f5aeee-97a6-4ed6-9d16-00b9139638eb.png)

How do I change the "WELCOME IN" to "WELCOME TO"?

**Comment by xixi52** [comment]
Hello! Add 
`.setText("message", "welcome to {server}")`

https://www.discord-canvas.com/functions/welcome#settext-optional

**Comment by Akihiro0666** [comment]
Thanks~
