### ISSUE TITLE
server responded with 404

### ISSUE THREAD

**Issue by BeLikeThugi** [xixi52/discord-canvas#51]
return onerror(new Error(`Server responded with ${res.statusCode}`))
                           ^

Error: Server responded with 404
    at C:\Users\x\Desktop\test\node_modules\canvas\lib\image.js:56:28
    at C:\Users\x\Desktop\test\node_modules\simple-get\index.js:89:7
    at IncomingMessage.<anonymous> (C:\Users\x\Desktop\test\node_modules\simple-concat\index.js:8:13)

**Comment by xixi52** [comment]
Have you change the URL of image ?
